export const countries = [
    { id: 1, name: "Afghanistan" },
    { id: 2, name: "Afrique du Sud" },
    { id: 3, name: "Albanie" },
    { id: 4, name: "Algérie" },
    { id: 5, name: "Allemagne" },
    { id: 6, name: "Andorre" },
    { id: 7, name: "Angola" },
    { id: 8, name: "Antigua-et-Barbuda" },
    { id: 9, name: "Arabie saoudite" },
    { id: 10, name: "Argentine" },
    { id: 11, name: "Arménie" },
    { id: 12, name: "Australie" },
    { id: 13, name: "Autriche" },
    { id: 14, name: "Azerbaïdjan" },
    { id: 15, name: "Bahamas" },
    { id: 16, name: "Bahreïn" },
    { id: 17, name: "Bangladesh" },
    { id: 18, name: "Barbade" },
    { id: 19, name: "Belgique" },
    { id: 20, name: "Belize" },
    { id: 21, name: "Bénin" },
    { id: 22, name: "Bhoutan" },
    { id: 23, name: "Biélorussie" },
    { id: 24, name: "Birmanie (Myanmar)" },
    { id: 25, name: "Bolivie" },
    { id: 26, name: "Bosnie-Herzégovine" },
    { id: 27, name: "Botswana" },
    { id: 28, name: "Brésil" },
    { id: 29, name: "Brunei" },
    { id: 30, name: "Bulgarie" },
    { id: 31, name: "Burkina Faso" },
    { id: 32, name: "Burundi" },
    { id: 33, name: "Cambodge" },
    { id: 34, name: "Cameroun" },
    { id: 35, name: "Canada" },
    { id: 36, name: "Cap-Vert" },
    { id: 37, name: "Chili" },
    { id: 38, name: "Chine" },
    { id: 39, name: "Chypre" },
    { id: 40, name: "Colombie" },
    { id: 41, name: "Comores" },
    { id: 42, name: "Congo (Brazzaville)" },
    { id: 43, name: "Congo (Kinshasa)" },
    { id: 44, name: "Corée du Nord" },
    { id: 45, name: "Corée du Sud" },
    { id: 46, name: "Costa Rica" },
    { id: 47, name: "Côte d'Ivoire" },
    { id: 48, name: "Croatie" },
    { id: 49, name: "Cuba" },
    { id: 50, name: "Danemark" },
    { id: 51, name: "Djibouti" },
    { id: 52, name: "Dominique" },
    { id: 53, name: "Égypte" },
    { id: 54, name: "Émirats arabes unis" },
    { id: 55, name: "Équateur" },
    { id: 56, name: "Érythrée" },
    { id: 57, name: "Espagne" },
    { id: 58, name: "Estonie" },
    { id: 59, name: "Eswatini (Swaziland)" },
    { id: 60, name: "États-Unis" },
    { id: 61, name: "Éthiopie" },
    { id: 62, name: "Fidji" },
    { id: 63, name: "Finlande" },
    { id: 64, name: "France" },
    { id: 65, name: "Gabon" },
    { id: 66, name: "Gambie" },
    { id: 67, name: "Géorgie" },
    { id: 68, name: "Ghana" },
    { id: 69, name: "Grèce" },
    { id: 70, name: "Grenade" },
    { id: 71, name: "Guatemala" },
    { id: 72, name: "Guinée" },
    { id: 73, name: "Guinée-Bissau" },
    { id: 74, name: "Guinée équatoriale" },
    { id: 75, name: "Guyana" },
    { id: 76, name: "Haïti" },
    { id: 77, name: "Honduras" },
    { id: 78, name: "Hongrie" },
    { id: 79, name: "Inde" },
    { id: 80, name: "Indonésie" },
    { id: 81, name: "Irak" },
    { id: 82, name: "Iran" },
    { id: 83, name: "Irlande" },
    { id: 84, name: "Islande" },
    { id: 85, name: "Israël" },
    { id: 86, name: "Italie" },
    { id: 87, name: "Jamaïque" },
    { id: 88, name: "Japon" },
    { id: 89, name: "Jordanie" },
    { id: 90, name: "Kazakhstan" },
    { id: 91, name: "Kenya" },
    { id: 92, name: "Kirghizistan" },
    { id: 93, name: "Kiribati" },
    { id: 94, name: "Koweït" },
    { id: 95, name: "Laos" },
    { id: 96, name: "Lesotho" },
    { id: 97, name: "Lettonie" },
    { id: 98, name: "Liban" },
    { id: 99, name: "Libéria" },
    { id: 100, name: "Libye" },
    { id: 101, name: "Liechtenstein" },
    { id: 102, name: "Lituanie" },
    { id: 103, name: "Luxembourg" },
    { id: 104, name: "Macédoine du Nord" },
    { id: 105, name: "Madagascar" },
    { id: 106, name: "Malaisie" },
    { id: 107, name: "Malawi" },
    { id: 108, name: "Maldives" },
    { id: 109, name: "Mali" },
    { id: 110, name: "Malte" },
    { id: 111, name: "Maroc" },
    { id: 112, name: "Marshall (Îles)" },
    { id: 113, name: "Mauritanie" },
    { id: 114, name: "Maurice" },
    { id: 115, name: "Mexique" },
    { id: 116, name: "Micronésie" },
    { id: 117, name: "Moldavie" },
    { id: 118, name: "Monaco" },
    { id: 119, name: "Mongolie" },
    { id: 120, name: "Monténégro" },
    { id: 121, name: "Mozambique" },
    { id: 122, name: "Namibie" },
    { id: 123, name: "Nauru" },
    { id: 124, name: "Népal" },
    { id: 125, name: "Nicaragua" },
    { id: 126, name: "Niger" },
    { id: 127, name: "Nigeria" },
    { id: 128, name: "Norvège" },
    { id: 129, name: "Nouvelle-Zélande" },
    { id: 130, name: "Oman" },
    { id: 131, name: "Ouganda" },
    { id: 132, name: "Ouzbékistan" },
    { id: 133, name: "Pakistan" },
    { id: 134, name: "Palaos" },
    { id: 135, name: "Panama" },
    { id: 136, name: "Papouasie-Nouvelle-Guinée" },
    { id: 137, name: "Paraguay" },
    { id: 138, name: "Pays-Bas" },
    { id: 139, name: "Pérou" },
    { id: 140, name: "Philippines" },
    { id: 141, name: "Pologne" },
    { id: 142, name: "Portugal" },
    { id: 143, name: "Qatar" },
    { id: 144, name: "République centrafricaine" },
    { id: 145, name: "République dominicaine" },
    { id: 146, name: "République tchèque" },
    { id: 147, name: "Roumanie" },
    { id: 148, name: "Royaume-Uni" },
    { id: 149, name: "Russie" },
    { id: 150, name: "Rwanda" },
    { id: 151, name: "Saint-Christophe-et-Niévès" },
    { id: 152, name: "Sainte-Lucie" },
    { id: 153, name: "Saint-Vincent-et-les-Grenadines" },
    { id: 154, name: "Salomon (Îles)" },
    { id: 155, name: "Salvador" },
    { id: 156, name: "Samoa" },
    { id: 157, name: "São Tomé-et-Principe" },
    { id: 158, name: "Sénégal" },
    { id: 159, name: "Serbie" },
    { id: 160, name: "Seychelles" },
    { id: 161, name: "Sierra Leone" },
    { id: 162, name: "Singapour" },
    { id: 163, name: "Slovaquie" },
    { id: 164, name: "Slovénie" },
    { id: 165, name: "Somalie" },
    { id: 166, name: "Soudan" },
    { id: 167, name: "Soudan du Sud" },
    { id: 168, name: "Sri Lanka" },
    { id: 169, name: "Suède" },
    { id: 170, name: "Suisse" },
    { id: 171, name: "Suriname" },
    { id: 172, name: "Syrie" },
    { id: 173, name: "Tadjikistan" },
    { id: 174, name: "Tanzanie" },
    { id: 175, name: "Tchad" },
    { id: 176, name: "Thaïlande" },
    { id: 177, name: "Timor oriental" },
    { id: 178, name: "Togo" },
    { id: 179, name: "Tonga" },
    { id: 180, name: "Trinité-et-Tobago" },
    { id: 181, name: "Tunisie" },
    { id: 182, name: "Turkménistan" },
    { id: 183, name: "Turquie" },
    { id: 184, name: "Tuvalu" },
    { id: 185, name: "Ukraine" },
    { id: 186, name: "Uruguay" },
    { id: 187, name: "Vanuatu" },
    { id: 188, name: "Vatican" },
    { id: 189, name: "Venezuela" },
    { id: 190, name: "Vietnam" },
    { id: 191, name: "Yémen" },
    { id: 192, name: "Zambie" },
    { id: 193, name: "Zimbabwe" }
];
