export const movies = [
    {
        "id": 1,
        "title": "The Exorcist",
        "country": "United States",
        "releaseYear": 1973,
        "director": "William Friedkin",
        "synopsis": "A young girl becomes possessed by a malevolent entity, leading her desperate mother to seek the help of two priests. Together, they confront the darkest forces in a battle for her soul.",
        "status": "APPROVED",
        "posterUrl": "https://example.com/hellraiser.jpg",
        "createdBy": 1,
        "createdAt": "2024-08-22T16:07:02",
        "genreName": ["Monstres", "Gore"]
    },
    {
        "id": 2,
        "title": "The Exorcist",
        "country": "United States",
        "releaseYear": 1973,
        "director": "William Friedkin",
        "synopsis": "A young girl becomes possessed by a malevolent entity, leading her desperate mother to seek the help of two priests. Together, they confront the darkest forces in a battle for her soul.",
        "status": "APPROVED",
        "posterUrl": "https://example.com/theexorcist.jpg",
        "createdBy": 1,
        "createdAt": "2024-08-24T11:54:40.47787",
        "genreName": ["Gore"]
    },
    {
        "id": 3,
        "title": "Hellraiser",
        "country": "Royaume-Uni",
        "releaseYear": 1987,
        "director": "Clive Barker",
        "synopsis": "Frank Cotton, un homme en quête de plaisirs inconnus, fait l'acquisition d’une mystérieuse boîte. Il y découvre un enfer rempli de souffrance et de plaisir.",
        "status": "APPROVED",
        "posterUrl": "https://example.com/texaschainsaw.jpg",
        "createdBy": 1,
        "createdAt": "2024-08-24T17:48:47.602493",
        "genreName": ["Gore"]
    },
    {
        "id": 4,
        "title": "Midsommar",
        "country": "United States",
        "releaseYear": 2019,
        "director": "Ari Aster",
        "synopsis": "A grieving woman joins her boyfriend on a trip to a remote Swedish village for a rare midsummer festival, only to become part of disturbing rituals.",
        "status": "APPROVED",
        "posterUrl": "https://example.com/midsommar.jpg",
        "createdBy": 1,
        "createdAt": "2024-09-22T11:00:00",
        "genreName": ["Horreur psychologique", "Folk horror"]
    },
    {
        "id": 5,
        "title": "Terrifier",
        "country": "United States",
        "releaseYear": 2016,
        "director": "Damien Leone",
        "synopsis": "On Halloween night, a maniacal clown named Art terrorizes two young women and anyone who stands in his way.",
        "status": "APPROVED",
        "posterUrl": "https://example.com/terrifier.jpg",
        "createdBy": 1,
        "createdAt": "2024-09-22T11:05:00",
        "genreName": ["Slasher", "Gore"]
    },
    {
        "id": 6,
        "title": "Sinister",
        "country": "United States",
        "releaseYear": 2012,
        "director": "Scott Derrickson",
        "synopsis": "A true-crime writer discovers a cache of disturbing home videos that hint at the presence of a deadly supernatural force.",
        "status": "APPROVED",
        "posterUrl": "https://example.com/sinister.jpg",
        "createdBy": 1,
        "createdAt": "2024-09-22T11:10:00",
        "genreName": ["Horreur surnaturelle", "Thriller"]
    },
    {
        "id": 7,
        "title": "The Shining",
        "country": "United States",
        "releaseYear": 1980,
        "director": "Stanley Kubrick",
        "synopsis": "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings.",
        "status": "APPROVED",
        "posterUrl": "https://example.com/theshining.jpg",
        "createdBy": 1,
        "createdAt": "2024-09-22T11:15:00",
        "genreName": ["Horreur psychologique", "Surnaturel"]
    },
    {
        "id": 8,
        "title": "Evil Dead",
        "country": "United States",
        "releaseYear": 1981,
        "director": "Sam Raimi",
        "synopsis": "Five friends travel to a remote cabin, where they unwittingly release flesh-possessing demons.",
        "status": "APPROVED",
        "posterUrl": "https://example.com/evildead.jpg",
        "createdBy": 1,
        "createdAt": "2024-09-22T11:20:00",
        "genreName": ["Monstres", "Gore"]
    },
    {
        "id": 9,
        "title": "Halloween",
        "country": "United States",
        "releaseYear": 1978,
        "director": "John Carpenter",
        "synopsis": "Fifteen years after murdering his sister on Halloween night, Michael Myers escapes from a mental hospital and returns to terrorize his hometown.",
        "status": "APPROVED",
        "posterUrl": "https://example.com/halloween.jpg",
        "createdBy": 1,
        "createdAt": "2024-09-22T11:25:00",
        "genreName": ["Slasher"]
    }
];
